services:
  lynx:
    build: .
    container_name: lynx-app
    restart: unless-stopped
    ports:
      - "3100"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_HOST=goadmin
      - DEFAULT_REDIRECT_HOST=go
      - PORT=3100
      - HOST=0.0.0.0
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=1
    networks:
      - lynx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/api/links"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lynx.rule=Host(`go.home`) || Host(`goadmin.home`)"
      - "traefik.http.services.lynx.loadbalancer.server.port=3100"

networks:
  lynx-network:
    driver: bridge
