services:
  lynx:
    build: .
    container_name: lynx-app
    restart: unless-stopped
    ports:
      - "${PORT:-3100}:${PORT:-3100}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_HOST=${ADMIN_HOST:-goadmin}
      - DEFAULT_REDIRECT_HOST=${DEFAULT_REDIRECT_HOST:-go}
      - PORT=${PORT:-3100}
      - HOST=0.0.0.0
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=1
    networks:
      - lynx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/api/links"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  lynx-network:
    driver: bridge
